version: '3.7'
services:
  app:
    build:
      context: .
      dockerfile: dev.Dockerfile
    ports:
      - ${PORT:-8081}:8081
    volumes:
      - .:/app
      - node_modules:/app/node_modules
    environment:
      ME_CONFIG_MONGODB_ENABLE_ADMIN: "false"
      ME_CONFIG_MONGODB_URL: "mongodb://admin:admin@localhost/db?authSource=admin"
volumes:
  node_modules:
